name: Update README

on:
  schedule:
    - cron: "0 2 * * *"  # Daily at 2 AM
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Update README
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = require('path');
            
            // Read current README
            const readmePath = path.join(process.cwd(), 'README.md');
            let readmeContent = fs.readFileSync(readmePath, 'utf8');
            
            // Update last updated timestamp
            const now = new Date().toISOString();
            const timestamp = `Last updated: ${now}`;
            
            // Add or update timestamp in README
            if (readmeContent.includes('Last updated:')) {
              readmeContent = readmeContent.replace(
                /Last updated:.*/,
                timestamp
              );
            } else {
              readmeContent = readmeContent.replace(
                /<!-- Invisible Analytics -->/,
                `<!-- Last Updated: ${timestamp} -->\n<!-- Invisible Analytics -->`
              );
            }
            
            // Write updated README
            fs.writeFileSync(readmePath, readmeContent);
            
            // Commit and push changes
            const { execSync } = require('child_process');
            execSync('git config --local user.email "action@github.com"');
            execSync('git config --local user.name "GitHub Action"');
            execSync('git add README.md');
            execSync('git commit -m "Update README timestamp"');
            execSync('git push');

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
